spring.profiles.active=dev
spring.application.name=SimpleConsumer
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL}
spring.kafka.consumer.group-id=${GROUP_ID}
spring.kafka.consumer.key-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.auto-offset-reset=${AUTO_OFFSET_RESET_MODE}
spring.kafka.consumer.properties.session.timeout.ms=${CONSUMER_SESSION_TIMEOUT}
spring.kafka.consumer.enable-auto-commit=${CONSUMER_AUTO_COMMIT}
spring.kafka.consumer.max-poll-records=${MAX_POOL_RECORDS}